### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isEmberPackagePath' of undefined

### ISSUE THREAD

**Issue by arjansingh** [KatalysatorAB/atom-ember-tabs#5]
### Reproduction Steps
1. Install the addon
2. Open an ember project at the project root
3. Type `cmd + shift + m`

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [ember-tabs](https://github.com/KatalysatorAB/atom-ember-tabs) package, v2.1.0
### Stack Trace

Uncaught TypeError: Cannot read property 'isEmberPackagePath' of undefined

```
At /Users/asingh/.atom/packages/ember-tabs/lib/ember-tabs.coffee:39

TypeError: Cannot read property 'isEmberPackagePath' of undefined
  at Object.module.exports.openFilePane (/Users/asingh/.atom/packages/ember-tabs/lib/ember-tabs.coffee:39:19)
  at atom-workspace.subscriptions.add.atom.commands.add.ember-tabs:open-file-pane (/Users/asingh/.atom/packages/ember-tabs/lib/ember-tabs.coffee:16:40)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```
### Commands

```
  7x -9:35.9.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -8:08.7.0 settings-view:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  4x -8:06.9.0 core:move-down (div.settings-view.pane-item)
     -8:01.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:54.4.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -4:49.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -4:48.6.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -4:48.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:45.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -4:45.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -4:38.8.0 project-manager:list-projects (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -4:37.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -3:08.8.0 ember-tabs:open-file-pane (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "followSymlinks": true,
    "projectHome": "/Users/arjan/code",
    "disabledPackages": [
      "linter-jscs",
      "node-resolver"
    ],
    "destroyEmptyPanes": false,
    "audioBeep": false,
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-syntax, v0.2.4
atom-material-ui, v0.6.3
ember-cli-helper, v0.9.0
ember-tabs, v2.1.0
language-ember-htmlbars, v0.3.0
linter, v1.9.1
linter-jshint, v1.2.1
linter-jsonlint, v1.0.1
minimap, v4.15.0
minimap-git-diff, v4.1.8
node-debugger, v1.1.9
pigments, v0.18.1
pretty-json, v0.4.1
project-manager, v2.6.5
trailing-spaces, v0.3.2
vim-mode, v0.62.0

# Dev
No dev packages
```

**Comment by erkie** [comment]
@arjansingh can you install `2.1.2` and close the issue if this issue is fixed? Thanks!

**Comment by arjansingh** [comment]
@erkie I don't get the error message anymore, but the add-on's pane is not opening. Any thoughts on why?

**Comment by erkie** [comment]
@arjansingh I identified some places that could cause the project to not load properly. Can you update to `2.1.3` and check if it works?
